id = "solace-theme"
name = "Solace"
version = "0.1.2"
schema_version = 1

authors = ["Bhavya Dang (bhavyadang.in)"]

description = "A minimal Zed theme with violet undertones and pastel syntax."

repository = "https://github.com/bhavya-dang/Solace"

themes = ["themes/solace.json"]
